### ISSUE TITLE
LotJ Race Browser 

### ISSUE THREAD

**Issue by Kinderjene** [Johnson336/LotJPlugins#7]
The race browser for Legends of the Jedi appears to be broken. When one starts a race scan it gags info but never fills the database. I am very new to coding but looking over the code I didn't see any glaring errors. Is this local or did something happen to cause it to stop working when the last era finished?

Cheers,
K

**Comment by Johnson336** [comment]
There were significant in-game updates to the formatting of showrace which was preventing the automatic scan from running successfully. This has been fixed in the newest update, plugin version 1.07 [see update here](https://github.com/Johnson336/LotJPlugins/commit/f9e45b6294b3feab8df5599dce77226cfce2d22f)
